name: CI

on:
  release:
    types: [created]
#  push:
#    branches:
#      - master

jobs:
  build-win:
    runs-on: windows-2019
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - name: Copy to C drive
        run: cp D:\a C:\ -Recurse
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - name: npm install, build and test
        working-directory: "C:/a/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
        run: |
          pwd
          npm install
          node build --arch x64
          node build --arch ia32
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win
          path: 'c:/a/**/build/out/*.zip'

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - name: npm install, build and test
        run: |
          npm install
          node build
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac
          path: 'build/out/*.zip'

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - name: npm install, build and test
        run: |
          npm install
          node build --arch x64
          node build --arch ia32
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: 'build/out/*.zip'

  build-release:
    needs: [build-win, build-macos, build-linux]
    name: "Build Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: win
          path: release/win
      - uses: actions/download-artifact@v2
        with:
          name: linux
          path: release/linux
      - uses: actions/download-artifact@v2
        with:
          name: mac
          path: release/mac

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: release/

      - name: Upload windows binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/win/*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Upload mac binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/mac/*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Upload linux binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/linux/*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
