name: Tagged Release

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: dawidd6/action-download-artifact@v2.16.0
        with:
          workflow: main.yml
          workflow_conclusion: success
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            linux/**/*.zip
            mac/**/*.zip
            win/**/*.zip
